### ISSUE TITLE
Issue due to space in theme name

### ISSUE THREAD

**Issue by 0xB4demeister** [PVautour/leftwm-theme-orange-forest#2]
Hi, I just wanted to play around with a fresh install of LeftWM in a new manjaro-i3 environment inside a virtual machine.
After installing all the necessary dependencies, your up script still failed for me, due to `feh` treating the space as a dividing symbol - therefore, it tried to find the background image `themes/Orange` instead of `themes/Orange Forest/background.jpg`
I installed your theme via the leftwm-theme utility https://github.com/leftwm/leftwm-theme

**Comment by pvautour** [comment]
Hmm ok I think I know how we could resole the issue. Adding `"` around the `$SCRIPTPATH` in my up and down scripts. 

Think you can test it and tell me if it resolved you issue? If so I will push it to master.

I'm not currently running leftwm right now so if you could do the validation it would really be great!

Checkout the branch called `fix-space-in-name-issue` to see the fix in action.

Thanks for opening an issue it always sucks when stuff like this happens, but the next guy/gal should have a working theme at least because of you. :)

**Comment by 0xB4demeister** [comment]
it tried your solution - it resolved some issues, but I needed to add the same adjustment to the 4 occurences of `$SCRIPTPATH` inside `polybar.config`, as well - to get it fully working.

**Comment by pvautour** [comment]
Ok nice thanks for testing. I applied this fix too.

I will keep the issue open for an extra week and close it if I don't hear from you again :)

Good day

**Comment by pvautour** [comment]
Ok closing the issue. Open a new one if something arises!

**Comment by pvautour** [comment]
Thanks for catching it, added the new fix too!
